### PR TITLE
Add test for homepage.

### PR DESCRIPTION
**Pull request by jonmast**
Just a test that checks the homepage for a success response so we have a
passing test for CodeShip.

### CODE REVIEW

**Comment by radiofreemattd** [comment]
The change to `schema.rb` is not something I was expecting. Is this something required by Codeship to keep track of whether or not it needs to push to Heroku?

Just want to make sure before we go monkeying about with db-kinds of things... :)

**Comment by jonmast** [comment]
The schema.rb change is from runnning `rake db:migrate`. The test will fail without it(it's the reason Saroar's PRs are failing on codeship).

**Comment by radiofreemattd** [comment]
Got it! I had run `bin/rake db:setup:all` locally, so I don't think I ever saw that and not sure I've ever noticed that in production. Thanks, man!

**Comment by mscoutermarsh** [comment]
schema.rb = :+1:. It's the current state of the DB structure. It allows us (and codeship) to setup the DB without running each individual migration.

**Comment by radiofreemattd** [comment]
Awesome. Apologies in advance if I am coming off neurotic...really not, just a bit deliberate after 1000 years of being a lawyer...

;) :+1:

**Pull request merged**
