### PR TITLE
Add SimpleFrom gem

### PR DESCRIPTION
**Pull request by saroar**
Simple form is awesome form :-)

### CODE REVIEW

**Comment by radiofreemattd** [comment]
In `_form.html.erb`, there appear to be instances where you are not properly opening and closing the ERB. Not sure why that would have occurred.

**Comment by saroar** [comment]
are you taking about this lib/templates/erb/scaffold/_form.html.erb ?

**Comment by radiofreemattd** [comment]
My bad - I just looked at another install of mine with SimpleForm and this is exactly the way this file looks, so apologies. No comments here.

**Comment by saroar** [comment]
So what next ?

**Pull request merged**
