### PR TITLE
Setup initial chessboard view

### PR DESCRIPTION
**Pull request by radiofreemattd**
A few comments about this Pull Request that hopefully explain what I was trying to do.

* `main.scss` pulls in the chessboard partial, which does a number of things, including defining some styles that make the board work, as well as some variables that I pulled out that will make customization of the board easier down the road.

* I tried to keep the view file in `show.html.erb` as DRY as possible, but please let me know if, as we would say in the legal profession, what I did is "too cute by half". In other words, I would like the intent of the code to be consistent with Ruby's self-documenting approach - if the math is contorted or if you think there is an easier or more flexible way to do this, I am absolutely all ears!

:+1: :smile:

### CODE REVIEW

**Comment by radiofreemattd** [comment]
For reference, this is what you should be seeing if you pull down this branch.

screen shot 2015-11-08 at 12 34 30 pm

**Comment by radiofreemattd** [comment]
One potential "bust" here might have been to not use the iterator to embed a unique ID in each div. I assume we are going to want that information available to the client at some point in the cycle (drag and drop?)...

**Comment by radiofreemattd** [comment]
We could also modify the function to remove the hard-coded `2`, which is to accommodate the `1px` border on either side. We can extract out `border` as a variable and let folks customize that as well, with the function just self-adjusting as a result.

**Comment by mscoutermarsh** [comment]
Great work :). I think this is all great as is & is ready to merge.

But in the spirit of throwing more things at you ;). I think you'll like this: http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

Generally CSS becomes a huge mess as a project gets bigger. In our case, not really an issue. But you'll see this in real world apps. Usually companies will create some sort of internal css naming conventions. "block, element, modifier" seems to be most popular at the moment.

So for example, you could do something like..

```css
.chess-board__space {
  height: $board-space-size-std;
  width: $board-space-size-std;
  float: left;
}
.chess-board__space--lite {
  background-color: $board-space-lite;
}
.chess-board__space--dark {
  background-color: $board-space-lite;
}
```

**Comment by radiofreemattd** [comment]
@mscoutermarsh I think this is worth adding and I think it is worth documenting as an internal team standard in a README that we post in the Resources list in Trello.

**Comment by mscoutermarsh** [comment]
:+1:

**Pull request merged**
