### PR TITLE
Cleanup views to use BS3 Grid System

### PR DESCRIPTION
**Pull request by radiofreemattd**
Semi-mobile friendly...

Assumes an 8 column grid on medium or larger devices, with a 12 column (full-width) grid on anything smaller.

### CODE REVIEW

**Comment by saroar** [comment]
i think all is good except one things for mobile device without this line our site will not work in mobile device if i am not wrong!!!

<head>
  <title>ChessApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

**Comment by radiofreemattd** [comment]
No, @saroar, you are absolutely correct. Let me add that change as a new commit to the PR.

**Comment by mscoutermarsh** [comment]
:+1:

**Comment by saroar** [comment]
So we can merge it now ?

**Comment by radiofreemattd** [comment]
@saroar Go for it!

**Pull request merged**
